---
title: "R Notebook"
output: html_document
date: "2023-10-17"
---

# install packages
```{r}
#install.packages("tidyverse")
```

# load packages
```{r}
library(tidyverse)
```

# view iris dataset
```{r}
View(iris)
```

# research question: how are the flower species different from one another?

# plot iris (petal width x petal length)
```{r}
ggplot(data = iris)+
  geom_point(mapping = aes(x = Petal.Width, y = Petal.Length, color = Species, size = Species, shape= Species))
```

# plot sepal width x length
```{r}
ggplot(data = iris)+
  geom_point(mapping = aes(x = Sepal.Width, y = Sepal.Length, color = Species))
```

# testing different plots
```{r}
ggplot(data = iris)+
  geom_col(mapping = aes(x = Species, y = Petal.Length, fill = Species))+ theme_light()
```

#load class data
```{r}
savic = read_csv("class_data.csv")
```

# basic info
```{r}
nrow(savic)

ncol(savic)

colnames(savic)
```

# research question: does the kind of co-occurence (direct / indirect) affect how people process old or new words?

# creating plot
```{r}
ggplot(data = savic)+
  geom_histogram(mapping = aes(x = as.numeric(rt)))
```

```{r}
objectdata = read_csv("objects.csv")
```

```{r}
objectdata = read_csv("objects.csv") %>%
  mutate(rt = as.numeric(rt),
         weight = as.factor(weight),
         shape = as.factor(shape))
  select(rt, weight, shape)
```

```{r}
condition_data = objectdata %>%
  filter(typeoftrial == "picture" & weight %in% c("Heavy", "Light") & shape %in% c("Normal", "Smashed") & correct == TRUE)%>%
  select(subject, rt, weight, shape, correct)
condition_data %>%
  summarize(mean_rt = mean(rt))
object_agg = condition_data %>%
  group_by(weight, shape) %>%
  summarize(mean_rt = mean(rt),
            sd_rt = sd(rt))
```

```{r}
ggplot(data = object_agg) +
  geom_col(mapping = aes(x = shape, y = mean_rt, fill = weight),
           position = "dodge") +
  theme_bw()+
  labs(title = "plot of RTs")+
  scale_fill_grey()
```

